# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Howard Dyer
email: me@howard-dyer.co.uk
description: "Graphic Designer | Front-End Developer"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.howard-dyer.co.uk"
twitter_username: howarddyer
github_username:  howarddyer

# Build settings
highlighter: rouge

exclude: ['*.css.map', '*.sass']

# Outputting
permalink: /:title.html
paginate: 5
paginate_path: "/page:num/"

sass:
    sass_dir: static/stylesheets

plugins: [jekyll-coffeescript, jekyll-watch, jekyll-assets, jekyll-paginate]
