# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Howard Dyer &mdash; Graphic Design and Front End Development
email: me@howard-dyer.co.uk
description: "I'm a Graphic Designer and Front-End Developer based in Cardiff"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.howard-dyer.co.uk"
twitter_username: howarddyer
github_username:  howarddyer

# Build settings
markdown: kramdown
highlighter: rouge
exclude: []

# Outputting
permalink: /:title.html
